### ISSUE TITLE
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by Anakin79** [andig/homebridge-fritz#27]
Always the same error "Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory".

Somewhere else I've seen that: "You can remove them by running: rm -rf ~/.homebridge/persist && rm -rf ~/.homebridge/accessories"
...but it didn't help :(

**Comment by andig** [comment]
Could you share a debug log of homebridge start?

**Comment by Anakin79** [comment]
pi@raspberrypi:~ $ sudo homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[10/1/2017, 10:21:29 AM] Loaded plugin: homebridge-fritz
[10/1/2017, 10:21:29 AM] Registering platform 'homebridge-fritz.Fritz!Box'
[10/1/2017, 10:21:29 AM] ---
[10/1/2017, 10:21:29 AM] Loaded plugin: homebridge-gpio-relay
[10/1/2017, 10:21:29 AM] Registering accessory 'homebridge-gpio-relay.relay'
[10/1/2017, 10:21:29 AM] ---
[10/1/2017, 10:21:29 AM] Loaded config.json with 0 accessories and 1 platforms.
[10/1/2017, 10:21:29 AM] ---
[10/1/2017, 10:21:29 AM] Loading 1 platforms...
[10/1/2017, 10:21:29 AM] [Fritz!Box] Initializing Fritz!Box platform...
[10/1/2017, 10:21:29 AM] Loading 0 accessories...
[10/1/2017, 10:21:30 AM] [Fritz!Box] Fritz!Box platform login successful
[10/1/2017, 10:21:30 AM] [Fritz!Box] Discovering accessories
[10/1/2017, 10:21:30 AM] [Fritz!Box] Outlets found: 087610254899,087610259299,087610279993,087610258571,116570028831
[10/1/2017, 10:21:31 AM] [Fritz!Box] Thermostats found: 109710206976,109710281584,109710501984,109710519112,109710502904,109710218464
[10/1/2017, 10:21:31 AM] [Fritz!Box] Sensors found: 
[10/1/2017, 10:21:31 AM] [Fritz!Box] Initializing platform accessory 'Guest WLAN'...
[10/1/2017, 10:21:31 AM] [Fritz!Box] Initializing platform accessory 'Musik Küche'...
[10/1/2017, 10:21:31 AM] [Fritz!Box] Initializing platform accessory 'Wohnzimmer'...
[10/1/2017, 10:21:31 AM] [Fritz!Box] Initializing platform accessory 'Kammerl'...
[10/1/2017, 10:21:31 AM] [Fritz!Box] Initializing platform accessory 'Garage'...
[10/1/2017, 10:21:31 AM] [Fritz!Box] Initializing platform accessory 'Zisterne'...
[10/1/2017, 10:21:31 AM] [Fritz!Box] Initializing platform accessory 'Maria Zimmer'...
[10/1/2017, 10:21:31 AM] [Fritz!Box] Initializing platform accessory 'Wohnzimmer'...
Unhandled rejection Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 24230275-6059-4ffd-a1a5-0707905fd041
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:257:13)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:367:24)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at /usr/local/lib/node_modules/homebridge-fritz/index.js:128:25
    at tryCatcher (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._fulfillPromises (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:668:14)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:694:18)
    at Async._drainQueue (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by andig** [comment]
Just look at the log file. Why are you adding “Wohnzimmer” twice? Two outlets with identical name apparently don’t work?

**Comment by ghost** [comment]
He just need to rename them in the fritzbox and add a number or so to it. he can later group them in the home app so he has 1 device

**Comment by Anakin79** [comment]
That problem is solved now. Thanks a lot!!!!!
...didn't know that there can be problems with the same name of plugs and thermostats (and didn't see it too).

**Comment by andig** [comment]
I'm reopening this since according to https://github.com/nfarina/homebridge/issues/203 this should actually work but doesn't.

Problem is most likely in https://github.com/nfarina/homebridge/blob/64864bac85ad3f3e642412152d3679d0022f05a0/app.js#L162. Need to investigate why two accessories of different type happen to generate identical uuids.

**Comment by andig** [comment]
> I'm reopening this since according to nfarina/homebridge#203 this should actually work but doesn't.

After some checking I've found that homebridge does **NOT** handle creating accessories of same name if they have different type:

    accessories.push(new FritzOutletAccessory(self, "foo"));
    accessories.push(new FritzThermostatAccessory(self, "foo"));
    callback(accessories);

Gives:

	/Users/andig/Documents/htdocs/homebridge/node_modules/hap-nodejs/lib/Accessory.js:258
	      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
	      ^

For `homebridge-fritz` this can be solved by adding the AIN as `uuid_base` parameter to `FritzPlatform.prototype` which I'll implement shortly.

**Comment by andig** [comment]
This has been partially fixed. You can have 2 devices with the same name now as long as they don't have the same type. I.e. you cannot have 2 outlets of name "Wohnzimmer", but you can have e.g. an outlet plus a thermostat.
